# Run tests manually in the Actions tab of the project
name: Postman Tests - Manual Trigger
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      RECIPIENT_EMAIL:
        description: 'Enter email of Recipient'
        default: 'kentdomaoal@gmail.com'
        required: true
      FEEDFILE:
        description: 'Enter path of the feed file'
        default: '/feed/run.json'
        required: true

jobs:
  test-api:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
      
        # Install Node on the runner
        - name: Install Node
          uses: actions/setup-node@v1
          with:
            node-version: "18.x"

        # Install the newman command line utility, also install the html and allure reporter
        - name: Install newman
          run: |
            npm install newman
            npm install -g newman-reporter-allure
            npm install -g newman-reporter-html
        
        - name: Run Postman Tests
          run: |
            npm run test -- ${{ inputs.FEEDFILE }}
        
        - name: Get Allure history
          uses: actions/checkout@v2
          if: always()
          continue-on-error: true
          with:
            ref: allure
            path: allure

        - name: Generate Allure Report
          uses: simple-elf/allure-report-action@master
          if: always()
          with:
            allure_results: reports/allure
            allure_history: allure-history

        - name: Deploy report to Github Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: allure
            publish_dir: allure-history

        - name: Send Report URL
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{secrets.MAIL_USERNAME}}
            password: ${{secrets.MAIL_PASSWORD}}
            subject: Allure Report - ${{ github.repository }} Build(${{ github.run_number }})
            to: ${{ inputs.RECIPIENT_EMAIL }}
            from: Github WorkFlow
            body: Test Completed. Please see report <a href="https://kentdomaoal.github.io/restapi-testing-postman-newman">here</a>